### ISSUE TITLE
Add yandex.[maps/navigator] and 2gis support

### ISSUE THREAD

**Issue by Drugoy** [fvasco/pinpoi#10]
Hello, I'd like to have a cross-application or above-application manager for geographical coordinates.
As far as I understand - that's what your application does (I just stumbled upon it in the F-Droid repo), but unfortunately it doesn't support neither <a href="https://play.google.com/store/apps/details?id=ru.dublgis.dgismobile&hl=en">2GIS</a> nor Yandex.<a href="https://play.google.com/store/apps/details?id=ru.yandex.yandexmaps&hl=en">Maps</a>/<a href="https://play.google.com/store/apps/details?id=ru.yandex.yandexnavi&hl=en">Navigator</a> map apps.
Could you, please, add support of them?

**Comment by fvasco** [comment]
Pinpoi can manage third party collection importing  these in various format, you need a common format (GPX, KML, ...) and a license to use data.

I don't know these application, which format is used by these application to export data?
Everyone can use this data?

**Comment by Drugoy** [comment]
Sorry for bothering you, I didn't know that your app relies on those apps' import/export abilities… For example 2GIS doesn't have neither export nor import.
And I don't know anything about licenses since I've never cared what's written there.
