### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [fvasco/pinpoi#11]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on Search Address
2. Orientation Change

Sequence 2:
1. Click on Category
2. Orientation Change

Sequence 3:
1. Click on Search Address
2. Enter Address and wait for result
3. Orientation Change

**Comment by fvasco** [comment]
Fixed in 1.5.2
