### ISSUE TITLE
as user I'd like to see different color markers on map so that I can easily understand how many they are of the same collection/category

### ISSUE THREAD

**Issue by tassoman** [fvasco/pinpoi#17]
When you see al the markers on the map they are all blue with a number on it, would be fine if they are of the same category/collection.

Having coloured collections or categories IMO can help understanding how many markers are the same. 

I think having a randomly assigned colour may be enough for start, otherwise a full feature would allow to choose the colour during creation/editing

**Comment by fvasco** [comment]
fixed in 1.4.7

**Comment by tassoman** [comment]
Thank you for being so fast!

**Comment by fvasco** [comment]
Yourwelcome

**Comment by Lee-Carre** [comment]
Seems to have regressed (v1.7.5).

**Comment by fvasco** [comment]
@Lee-Carre can you explain?
Colors are consistent in each search.

**Comment by Lee-Carre** [comment]
@fvasco

Apologies.

From the OP:

> When you see al the markers on the map they are all blue …

Even with v1.7.6 I still observe the described behaviour. I never see any other colours, despite having multiple sets of PoIs loaded (I'm different categories), and querying an area which has matches from multiple sets / categories.

I'll see if I can figure out how to upload a display-capture image.

**Comment by fvasco** [comment]
Yes, all markers are blue, but the number inside has a distinctive colour.
Can you confirm, @Lee-Carre?

**Comment by Lee-Carre** [comment]
> all markers are blue, but the number inside has a distinctive colour. Can you confirm[…]?

Ironically, I'm having trouble with displaying the map at all. Often (but not always) it stalls at a mostly-white display. No background map, no radius rings, no PoI markers (of any colour 😆). See #27.

I'm puzzled, still, as to what conditions trigger it (for reliable reproduction steps).

🤷‍♂️

**Comment by fvasco** [comment]
@Lee-Carre
[The library's support has been discontinued](https://web.archive.org/web/20220313171236/https://leafletjs.com/).

**Comment by Lee-Carre** [comment]
> [The library's support has been discontinued](//web.archive.org/web/20220313171236/https://leafletjs.com/).

Ah, and PinPoi depends on its hosted services, rather than being part of the app and merely fetching OSM Carto tiles?

Seems like that's a separate matter to resolve (first).

Else, how does map rendering work in PinPoi?

Though, even before the Russia–Ukraine conflict, I had trouble with loading the map, sometimes.
Though, seems that debugging is not possible, for now.

**Comment by fvasco** [comment]
@Lee-Carre
PinPoi uses LeafLet and OSM to render map.

https://github.com/fvasco/pinpoi/blob/master/app/src/main/java/io/github/fvasco/pinpoi/PlacemarkListActivity.kt#L150

Any contribution is welcome.

**Comment by Lee-Carre** [comment]
Today, I've noticed other projects which are using Leaflet without trouble (maps displaying as expected).

Moments ago, I also successfully had PinPoi render a map of PoIs. Unfortunately, all from the same category, so I'm _still_ unable to confirm (or refute) the question about colouring of markers / pins 🤨.

I'm suspecting that it has something to do with how many nodes are in the set. A small count of PoIs tends to succeed more often than many.

**Comment by Lee-Carre** [comment]
@fvasco

> all markers are blue, but the number inside has a distinctive colour. Can you confirm[…]?

Right. I finally found a combination which worked. 🥳🕺

So, I **can, indeed, confirm** your description: each pin is blue (regardless of category), but the numeral it shows is differently-coloured (seemingly based on dataset within a category, based on how I'm invoking it).

---

Trouble is, they're not clearly distinct (especially when displaying many pins). So, what I think the OP was seeking, was for the entire pin to be colour-coded (not just the numeral), so that they're very clearly distinct.

Is this some limitation of Leaflet, that all pins must be blue?

**Comment by tassoman** [comment]
If I got your question, Leaflet Markers are made with a [DefaultIcon](https://github.com/Leaflet/Leaflet/blob/main/src/layer/marker/Icon.Default.js) 🤔

**Comment by fvasco** [comment]
Currently custom icon is generated using the `Leaflet.Icon.Glyph` library.
I already [pointed to interesting code](https://github.com/fvasco/pinpoi/issues/17#issuecomment-1066429965).

Enhance this feature is an interesting task, I see some issues:

1. we need to find some candidate colours for new markers, these colours do have to be confused with map items.
2. we need to find/draw these markers, without any legal issues.
3. we have to find good pairs of marker colour / text colour, keeping in mind colour blindness issue.

Again, contributions are welcome.
