### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by mayowadavid** [fvasco/pinpoi#19]
Hello i find your application very lovely, as it help to Imports thousand points of interest a user GPS navigator in their respective Android mobile device. Then i intend to make a logo which will help communicate the purpose of the application.
![pinpoi-compound-sample~2.png](https://steemitimages.com/DQmcyRdoKrCgKwqA9Z8g9FnxmUDPqT5HbJpx4qKKYJ5CMq4/pinpoi-compound-sample~2.png)
Below is the link to all the files, if you like the logo you can use it.
https://drive.google.com/folderview?id=1Qck8XuG0Yhsq4Ls24VqwVDYNxvHTpCc2
Cheers!

**Comment by fvasco** [comment]
Hi @mayowadavid 
I really appreciate your interest.
changing the launcher icon is a delicate action, so I wish to be sure of final outcome.

Please take some time to reconsider your proposal, if you wish apply you style on PinPoi app then resume this issue the May 14th.

Any other considerations is welcome.

Thank you

**Comment by mayowadavid** [comment]
Hmmm..as you said, changing the logo icon is a delicate action and you will need some time to check how  the finish look will look like. I have decided to add an extra file containing the logo alone.


![pinpoi-main-logo11.png](https://steemitimages.com/DQmNpXLHvLErkcAYGBZxHEisB8Gpwnf5WGnjtmkLseMnMJB/pinpoi-main-logo11.png)
If you want any other action to be carry out, i will make them available as soon as possible.
Cheers!

**Comment by fvasco** [comment]
Hi @mayowadavid 
any news?

**Comment by mayowadavid** [comment]
Hello @fvasco 
#### Below is the finished design of the logo i made for your application, hope you like it.
![Screenshot_20180514-204756~2.png](https://steemitimages.com/DQmQ7WXxs1xnhfnRJtgKuW7WwqdkRDsgVrWNi2C9wpxZh6r/Screenshot_20180514-204756~2.png)

![pinpoi12.png](https://steemitimages.com/DQmaMLwoRNS66rpxCsrSXY4k6F5viZA9KidhxXiZzc5Z9uL/pinpoi12.png)

Below is the link to all the original files 
https://drive.google.com/folderview?id=1Qck8XuG0Yhsq4Ls24VqwVDYNxvHTpCc2

**Comment by fvasco** [comment]
Well done @mayowadavid 
Please perform a color blindness check on your final result and ensure a sufficient contrast for each issue, you can use http://www.color-blindness.com/coblis-color-blindness-simulator/ (*launcher must be easy to remember and recognize for everyone - with or without glasses*)

When you are ready, please submit a pull request changing resources in `pinpoi/app/src/main/res/mipmap-...` folders
Then please put source image file in a newly create `doc/launcher.ai` folder

Warning: your pull request will be subject to PinPoi GPL licence.

**Comment by mayowadavid** [comment]
@fvasco
I have made all necessary changes and i have also submit a pull request.

**Comment by mayowadavid** [comment]
@fvasco 
Is there anything else you think need to be adjusted?

**Comment by fvasco** [comment]
Hi @mayowadavid 
the pull request was wrong, so I worked to merge your idea.
Your proposal is fine, I am testing the blue one on my phone to prove your work.
However I have some concern about it, the compass is pretty small, it is blue on blue background and the red part looks like a spot.

Your first proposal was fine and your enhancement is interesting.
Wish you try to use a thin darker border, a lighter background, a bigger compass and remove the shadow?

**Comment by mayowadavid** [comment]
Ok i will get that done as soon as possible

**Comment by mayowadavid** [comment]
@fvasco 
This is what i came up with after considering everything you said

![pinpoi-main-logo16.png](https://steemitimages.com/DQmVBa55XxtiM4BfGR9NEUTcMBUDD7T8FEjxpf9Vrywdhgf/pinpoi-main-logo16.png)

**Comment by mayowadavid** [comment]
And concerning the merge i will check it out and make every necessary correction

**Comment by mayowadavid** [comment]
@fvasco 
i have corrected everything 
- The red color that look like a spot
- A thin darker border
- A lighter background
- A bigger compass 
- i have also remove the shadow
- All pinpoi dpi file have also been uploaded
 - Folder to source file have been also been created along with the new pull request.

**Comment by mayowadavid** [comment]
@fvasco hope there is no longer problem with the merge request, if there is i guess it will be due to not having write access

**Comment by fvasco** [comment]
@mayowadavid I will test it, thanks.

**Comment by mayowadavid** [comment]
Ok @fvasco i will be waiting for the outcome.

**Comment by mayowadavid** [comment]
@fvasco 
Here is a preview of 
48*48 px view of the icon.

![pinpoi-main-mdpi-48-sharp](https://user-images.githubusercontent.com/34623610/40308485-5b13c9fa-5cfe-11e8-8727-dbe9d4363d68.png)
***
72*72 view 
![pinpoi-main-mdpi-72sharp](https://user-images.githubusercontent.com/34623610/40308687-f728f004-5cfe-11e8-814f-948ce0bd4719.png)

Is the compass small at this size or should i increase it?

**Comment by fvasco** [comment]
Fine @mayowadavid, can you provide an example of increased one?

**Comment by mayowadavid** [comment]
96*96
![pinpoi-main96](https://user-images.githubusercontent.com/34623610/40310610-3bf143b6-5d05-11e8-8d2e-599254ae1033.png)
***
144*144
![pinpoi-main-144](https://user-images.githubusercontent.com/34623610/40310634-4f148354-5d05-11e8-859c-f2f892d1ff6c.png)
***
300*300
![pinpoi-main300](https://user-images.githubusercontent.com/34623610/40310647-5fb33f66-5d05-11e8-96bf-4ca481803ea7.png)
@fvasco  this are are increased size

**Comment by fvasco** [comment]
Oops,
sorry @mayowadavid 
Can you increase the compass size in 48x48 preview?

**Comment by mayowadavid** [comment]
I will do that now

**Comment by mayowadavid** [comment]
![pinpoi-mdpi-48](https://user-images.githubusercontent.com/34623610/40311665-76daae6a-5d08-11e8-898b-645c00312ad2.png)
 @fvasco here is it

**Comment by fvasco** [comment]
Congratulations @mayowadavid 
I like it!
You should update your pull request following my previous instructions.

Change the resurse in `pinpoi/app/src/main/res/mipmap-...`, replace old files respecting the original image size.
Add the `doc/launcher.ai` file
Don't change `README.md` or other files, don't add `app/src/main/res/Source file changing resources` or anything else.

Your pull request have to contain only one commit with all these changes, please review your own branch history.

**Comment by mayowadavid** [comment]
Ok i will do that now

**Comment by mayowadavid** [comment]
@fvasco 
I have created the pull request

**Comment by fvasco** [comment]
Hi @mayowadavid 
your pull request contains 23 commits, you have to squash all into a single one
you should delete the `app/src/main/res/mipmap-hdpi/Source file` file and put the `launcher.ai` in a `doc` folder (create the `doc/launcher.ai` file)

Finally the images should not have any margin, see https://github.com/mayowadavid/pinpoi/blob/fa18d9c0b3df2c6e817545b75075267afdafd331/app/src/main/res/mipmap-xhdpi/pipoi-xhdpi.png for example

**Comment by mayowadavid** [comment]
@fvasco 
I make all necessary changes but am stuck with squashing all the commit as a single commit

**Comment by mayowadavid** [comment]
@fvasco a friend of mine have help me make the pull request all the file have also been amended

**Comment by fvasco** [comment]
Ok @mayowadavid 
I will check the PR this week, there are many commits, I will squash those.

**Comment by fvasco** [comment]
I checked your pull request yesterday.
I noticed that the logo is not symmetric, the left line is sloping.

Moreover what is the ` app/src/main/res/minmap` folder?
All launcher icons are stored in `pinpoi/app/src/main/res/mipmap-...` folders. **You have to replace the files**

**Comment by mayowadavid** [comment]
I did not know how to squash all the commit as a single commit all the files you need are [Here](https://drive.google.com/folderview?id=1Qck8XuG0Yhsq4Ls24VqwVDYNxvHTpCc2).
There is no longer slope.

**Comment by fvasco** [comment]
Why the compass is no more centered in the circle?

**Comment by mayowadavid** [comment]
I have check and add guide to all the files they are all centerally align.
Check to view with guide i included in all the files

**Comment by mayowadavid** [comment]
@fvasco 
Hope there is no longer problem with the logo

**Comment by fvasco** [comment]
Me too, I will check it

**Comment by fvasco** [comment]
Ok,
do you wish to update your pull request?

**Comment by mayowadavid** [comment]
Yea but i don't know how to squash all the commit as a single commit

**Comment by fvasco** [comment]
I will squash it using GitHub

**Comment by mayowadavid** [comment]
Ok i will submit them now

**Comment by mayowadavid** [comment]
Done

**Comment by fvasco** [comment]
The commit was wrong, again.
The `mipmap-mdpi/pinpoi-mdpi.png` is 1000 x 1000, not 48 x 48, moreover you have to replace the `mipmap-mdpi/ic_launcher.png` file.

Finally an *user* noted a mistake in the icon, if you draw a big X on it then you will see its asymmetry.

**Comment by mayowadavid** [comment]
Oops my bad, i was trying to avoid a slope that was why it turn out that way

**Comment by fvasco** [comment]
Merged and fixed
