### ISSUE TITLE
Extra text in [Collection] chooser

### ISSUE THREAD

**Issue by annihat** [fvasco/pinpoi#23]
From the main screen, [Collection] button produces text extra to the name I edited in #22

**Comment by annihat** [comment]
This extra text is from the KMZ file http://download.bournemouth.ac.uk/apsci/srp/Seeing-Beneath-Stonehenge.kmz

**Comment by fvasco** [comment]
@annihat I cannot reproduce this issue, can you expose me a use-case or provides some screenshots?

**Comment by fvasco** [comment]
@annihat any news? Should I close this issue?

**Comment by annihat** [comment]
Hi, really sorry, I didn't see notifications for this so didn't come back. 
I can't remember what was going wrong & it works now with the downloaded file though there is a certificate problem (probably a missing root certificate) on my new phone so I can't test the online offering
