### ISSUE TITLE
Odd copy'n'paste behaviour

### ISSUE THREAD

**Issue by annihat** [fvasco/pinpoi#24]
From [Manage collections], editing one collection, it is possible to long-press select the address but the cut/copy/paste dialog is absent. 
It is possible to drag the address into the [description] field where the cut/copy/paste dialog is present

**Comment by fvasco** [comment]
On my test smartphone I can use copy/past on "source address".
Adding a "paste" button will fix your issue?

**Comment by annihat** [comment]
It was the [copy] button I wanted, but I didn't see [paste] either. 

Maybe it's my phone -- Samsung J500FN, like so many others they're reputed to suffer a lack of memory

**Comment by fvasco** [comment]
Thanks
I will add a "replace with clipboard content" button as a workaround for this issue.
