### ISSUE TITLE
grpc failed

### ISSUE THREAD

**Issue by eddydc** [fvasco/pinpoi#30]
When searching an address/location pinpoi returns "GRPC failed" when trying to geolocate the address and on is unable to search on address anymore.

**Comment by fvasco** [comment]
Hi @eddydc,
Pinpoi uses the [Geocoder](https://developer.android.com/reference/android/location/Geocoder#getFromLocationName(java.lang.String,%20int)) to search address on your device and it requires internet connection.

Do you use a well supported Android version on your phone?
Do you get this error when internet connectivity is working?

I suppose that [a better description can be provided](https://issuetracker.google.com/issues/64247769).

**Comment by eddydc** [comment]
I’m using minpool > 1 year and of course with an internet connection. Tried borg WiFi as 4g. I’ve submitted this issue with the same machine btw. Having said this, it works today. So I guess it was a temp glitch of the geocoder

**Comment by fvasco** [comment]
> So I guess it was a temp glitch of the geocoder

It happens to me too.
