### ISSUE TITLE
RFE: `GeoJSON` format

### ISSUE THREAD

**Issue by Lee-Carre** [fvasco/pinpoi#34]
One of my uses for PinPoi is with [map](//www.openstreetmap.org/) surveying.

In the OSM realm, [GeoJSON](//geojson.org/) is a commonly-used format.

Sometimes, a dataset isn't published (or a tool doesn't output) in any format which PinPoi can parse (i.e. only GeoJSON).

Thus, it would be most helpful to use this format in PinPoi.

**Comment by fvasco** [comment]
It looks interesting.
Unfortunately this standard misses some important attribute, can you provide me an example?

**Comment by Lee-Carre** [comment]
> can you provide me an example?

[GeoJSON.org](//geojson.org/) cites [RFC 7946](//tools.ietf.org/html/rfc7946), which includes [RFC 7946 § 1.5 Example](//datatracker.ietf.org/doc/html/rfc7946#section-1.5).

I'll have to hunt for a _good_ (correct / accurate, and feature-complete) example.

In the meantime, a meta-example; some tools which generate GeoJSON:
* [GeoJSON.io](//geojson.io/)
* [OSM2GeoJSON](//tyrasd.github.io/osmtogeojson/)
* [Overpass Turbo](//overpass-turbo.eu/) (after generating a query, look under “`Export`”)

**Comment by fvasco** [comment]
Take a look to the version 1.8.0.

**Comment by Lee-Carre** [comment]
> > can you provide me an example?
> 
> […]
> 
> I'll have to hunt for a _good_ (correct / accurate, and feature-complete) example.

While imperfect (not _necessarily_ (although still likely) _strictly_ valid & correct (spec-compliant), or feature-complete), some real-world samples (that're well-used) are to be found at
* [USGS § Earthquakes § Data Feeds](//earthquake.usgs.gov/earthquakes/feed/)
  * [GeoJSON Summary Format](//earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php)
  * [GeoJSON Detail Format](//earthquake.usgs.gov/earthquakes/feed/v1.0/geojson_detail.php)

[Edit to add:] An OSM-centric sample (generated, depending on the area viewed / selected) is
* @rjw62's [#SurveyMe tool](//osm.mathmos.net/survey/)
  * working example (simplified / minimal): [`//osm.mathmos.net/survey/data.cgi?lat=49.2&lon=-2.1`](//osm.mathmos.net/survey/data.cgi?lat=49.2&lon=-2.1) (`fmt` seems to default to GeoJSON, without a value to explicitly force it)

---

> […] some tools which generate GeoJSON:

FYI; I [added another to the list](/fvasco/pinpoi/issues/34#issuecomment-1066189829).

---

> Take a look to the version `1.8.0`.

Will do! 🙂
Waiting for [F-Droid to build & publish](//www.f-droid.org/packages/io.github.fvasco.pinpoi). I'll report back after installing & testing.

**Comment by fvasco** [comment]
@Lee-Carre
should be closed this issue?

**Comment by Lee-Carre** [comment]
> should be closed this issue?

Apologies for my recent absence.
* technical difficulties
* health issues

I have not yet had chance to test, and am unsure of when I'd be able to.

I'm sure that you did decent testing as part of your implementation process.

So, yes, closing this issue is probably best. It can always be re-opened if needed.

I do intend to report back, eventually, if only to confirm that GeoJSON functions as expected. Else with suggestions for tweaks.

Once again, thankyou for your prompt efforts, @fvasco. 🙂👍
