### ISSUE TITLE
Use a proper map library?

### ISSUE THREAD

**Issue by opk12** [fvasco/pinpoi#35]
[OsmDroid](https://github.com/osmdroid/osmdroid) is a library that can show markers on a slippy map. This is
- faster, and better security-wise, than downloading JS from unpkg
- more maintainable than hard-coding html or generating html at runtime
- has neat features: auto-groups markers based on the zoom, shows current location, ...
- enables future support for customizing the basemap, showing tracks, ...

**Comment by fvasco** [comment]
Good idea, done in 1.10.0.

Thank you.
