### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by opk12** [fvasco/pinpoi#36]
<s>When the search button is tapped and `show on map` is checked, why does the app connect to the developer's domain `fvasco.github.io`? An app that accesses the location and points of interest should not do unnecessary network connections to a website that may be compromised etc.

The f-droid issue is [here](https://gitlab.com/fdroid/fdroiddata/-/issues/2822)</s>

Error on my part, see below

**Comment by licaon-kter** [comment]
With https://f-droid.org/en/packages/org.microg.nlp.backend.nominatim/ installed I only see connections from Nominatim and not from this app. That github domain is not accessed.

It does open that in the web browser if I use "website" from menu.

**Comment by opk12** [comment]
Sorry, the app connects to `leaflet.github.io` instead, the well-known map renderer.

For the future myself: the domains in NetGuard's logs are guessed from IP address equality and their issue of different domains resolving to the same IP is well-known.

**Comment by licaon-kter** [comment]
@opk12 in Netguard in app details you can touch a domain and that menu has the top entry with a selector if there are multiple domain on that IP

**Comment by opk12** [comment]
@licaon-kter Thank you. I'm actually switching to Rethink at this point.
