### ISSUE TITLE
Can't import exported KMZ from Organic Maps

### ISSUE THREAD

**Issue by brunetton** [fvasco/pinpoi#37]
Hi

I tried to import a KMZ file exported from [Organic Maps](https://organicmaps.app) but this results in an error in PinPoi saying the file contains no POI.

## Steps to reproduce
- add some POIs in [Organic Maps](https://organicmaps.app) app
- export those POIs ("export as a file" from context menu of POIs group in app
- import this file onto PinPoi

Thanks !

**Comment by fvasco** [comment]
Hi @brunetton,
thank you for this issue.

Did you tested the KMZ file with some other tool?
You can use a online viewer, like https://www.sunearthtools.com/tools/gps-view.php
Is it work as expected?

Can you share a non-working KMZ?
Please attach it in this issue, thanks.

**Comment by brunetton** [comment]
> Hi @brunetton, thank you for this issue.
> 
> Did you tested the KMZ file with some other tool? You can use a online viewer, like https://www.sunearthtools.com/tools/gps-view.php Is it work as expected?
> 

Yes it works with this tool (and Josm, and also QGIS)

> Can you share a non-working KMZ? Please attach it in this issue, thanks.

Here is a little one, with only 2 POIs: [PinPoi Pof.zip](https://github.com/fvasco/pinpoi/files/11491594/PinPoi.Pof.zip) (zipped because strangely kmz files are not allowed)


Thanks !

**Comment by fvasco** [comment]
Fixed in 1.10.3.

Thank you for contributing to free software!
