### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by alanthehat** [fvasco/pinpoi#9]
Hi, 
Are there any instructions for this app? 
I'm not clear what this app does & I have no idea how to make it do whatever it does

**Comment by fvasco** [comment]
Hi alanthehat,
thank you for your feedback.

There isn't any manual now, I wish to write it and I am looking for contributors ;)

I try to write you a little example to show PinPoi.
- Open Pinpoi
- Tap "MANAGE COLLECTIONS"
- Tap "+ BUTTON" on bottom right to create a new collection
- In collection name write "World Heritage List" or whatever you want
- In source URL paste "http://whc.unesco.org/en/list/kmz"   (*)
- Tap ↻ arrow button on top right (use data connection)
- Back to main page
- Compile the form: latitude: 50, longitude: 0, Search range: >60km
- Tap search
- PinPoi shows "Le Havre, France", short tap open detail, long tap open map
- In POI detail you cat set it as favourite (★), write a note ant open a map (short tap open map, long tap open app selector)

PinPoi 0.3.0 can shows POIs on map.

I hope this help you,
Francesco

(*) Terms and Conditions of Use: http://whc.unesco.org/en/syndication/

**Comment by fvasco** [comment]
See https://fvasco.github.io/pinpoi/
